# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.

[[main]]
  name = "Home"
  url = "/"
  weight = 1

[[main]]
  name = "News"
  pageRef = "news"
  weight = 10

[[main]]
  name = "Downloads"
  pageRef = "downloads"
  weight = 20

[[main]]
  name = "Wiki"
  url = "https://tapto.wiki"
  weight = 30

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 40

[[main]]
  name = "Zaparoo.com"
  url = "https://zaparoo.com"
  weight = 50

[[subnavigation]]
 name = "Contributors"
 pre = "heart"
 url = "https://tapto.wiki/Contributors"
 weight = 5

[[subnavigation]]
 name = "GitHub"
 pre = "github"
 url = "https://github.com/ZaparooProject/"
 weight = 10

[[subnavigation]]
 name = "Discord"
 pre = "discord"
 url = "https://wizzo.dev/discord"
 weight = 20

[[subnavigation]]
 name = "Reddit"
 pre = "reddit"
 url = "https://reddit.com/r/Zaparoo"
 weight = 30

[[subnavigation]]
 name = "RSS"
 pre = "rss-square"
 url = "/news/index.xml"
 weight = 40

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
  name = "Terms"
  pageRef = "/terms"
  weight = 5

[[footer]]
  name = "Privacy"
  pageRef = "/privacy"
  weight = 10

[[footer]]
  name = "Contact"
  pageRef = "/contact"
  weight = 30

[[footer]]
  name = "Zaparoo.com"
  url = "https://zaparoo.com"
  weight = 50
