#!/usr/bin/env node
// Updates the homepage stats for zaparoo.org and zaparoo.com from live sources.
//
// Sources:
//   - Downloads: total release asset downloads of ZaparooProject/zaparoo-core (GitHub API)
//   - Discord members: invite widget API (approximate_member_count), invite code
//     resolved from the zaparoo.org/discord redirect
//   - GitHub stars: sum across non-fork ZaparooProject repos (GitHub API)
//   - Platforms: manual constant below (auto-counting is unreliable: core has
//     unreleased platform dirs, docs list platforms core doesn't ship yet)
//
// Writes:
//   - <zaparoo.org>/src/data/stats.ts        (display strings in org style + raw values)
//   - <zaparoo.com>/src/data/stats.ts        (generated module in com style)
//
// Usage: node scripts/update-stats.mjs
// Display values are rounded DOWN to clean public numbers.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const PLATFORM_COUNT = 11; // keep in sync with zaparoo.org/docs/platforms
const DISCORD_INVITE_FALLBACK = 'jNdWq52rBP';

const orgRepo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const comRepo = path.resolve(orgRepo, '..', 'zaparoo.com');

async function getJson(url, headers = {}) {
  const res = await fetch(url, { headers: { 'User-Agent': 'zaparoo-stats-script', ...headers } });
  if (!res.ok) throw new Error(`${url} -> HTTP ${res.status}`);
  return res.json();
}

async function fetchDownloads() {
  let total = 0;
  for (let page = 1; ; page++) {
    const releases = await getJson(
      `https://api.github.com/repos/ZaparooProject/zaparoo-core/releases?per_page=100&page=${page}`
    );
    if (releases.length === 0) break;
    for (const release of releases) {
      for (const asset of release.assets ?? []) total += asset.download_count ?? 0;
    }
    if (releases.length < 100) break;
  }
  if (total === 0) throw new Error('download count came back as 0, refusing to write');
  return total;
}

async function fetchStars() {
  let total = 0;
  for (let page = 1; ; page++) {
    const repos = await getJson(
      `https://api.github.com/orgs/ZaparooProject/repos?per_page=100&page=${page}`
    );
    if (repos.length === 0) break;
    for (const repo of repos) {
      if (!repo.fork) total += repo.stargazers_count ?? 0;
    }
    if (repos.length < 100) break;
  }
  return total;
}

async function fetchDiscordMembers() {
  let code = DISCORD_INVITE_FALLBACK;
  try {
    const res = await fetch('https://zaparoo.org/discord', { redirect: 'manual' });
    const location = res.headers.get('location') ?? '';
    const match = location.match(/discord\.gg\/([\w-]+)/);
    if (match) code = match[1];
  } catch {
    // fall back to the hardcoded invite code
  }
  const invite = await getJson(`https://discord.com/api/v10/invites/${code}?with_counts=true`);
  const count = invite.approximate_member_count;
  if (!count) throw new Error('Discord invite API returned no member count');
  return count;
}

// Round down to a clean public number: nearest 10k above 100k, nearest 5k
// above 50k, nearest 1k above 10k, nearest 100 above 1k.
function roundDown(n) {
  const step = n >= 100_000 ? 10_000 : n >= 50_000 ? 5_000 : n >= 10_000 ? 1_000 : n >= 1_000 ? 100 : 10;
  return Math.floor(n / step) * step;
}

const compact = (n) => (n >= 1_000 ? `${(n / 1_000).toFixed(n % 1_000 === 0 ? 0 : 1).replace(/\.0$/, '')}k` : `${n}`);

function writeOrgStats(values) {
  const file = path.join(orgRepo, 'src', 'data', 'stats.ts');
  fs.mkdirSync(path.dirname(file), { recursive: true });
  const content = `// GENERATED by scripts/update-stats.mjs — do not edit by hand.
// Refresh with: pnpm stats (raw values as of ${values.updated})
const siteStats = {
  downloads: '${compact(values.downloads)}',
  discordMembers: '${compact(values.discordMembers)}',
  githubStars: '${compact(values.githubStars)}',
  platforms: '${values.platforms}',
} as const;

export default siteStats;
`;
  fs.writeFileSync(file, content);
  console.log(`wrote ${file}`);
}

function writeComStats(values) {
  if (!fs.existsSync(comRepo)) {
    console.warn(`warning: ${comRepo} not found, skipping zaparoo.com`);
    return;
  }
  const file = path.join(comRepo, 'src', 'data', 'stats.ts');
  const content = `// GENERATED by ../zaparoo.org/scripts/update-stats.mjs — do not edit by hand.
// Refresh with: pnpm stats (raw values as of ${values.updated})
export const stats = [
  { value: '${compact(values.downloads)}', label: 'Downloads' },
  { value: '${compact(values.discordMembers)}', label: 'Community Members' },
  { value: '${values.platforms}', label: 'Platforms' },
] as const;
`;
  fs.writeFileSync(file, content);
  console.log(`wrote ${file}`);
}

const [downloads, stars, discordMembers] = await Promise.all([
  fetchDownloads(),
  fetchStars(),
  fetchDiscordMembers(),
]);

const values = {
  downloads: roundDown(downloads),
  discordMembers: roundDown(discordMembers),
  githubStars: roundDown(stars),
  platforms: PLATFORM_COUNT,
  raw: { downloads, discordMembers, githubStars: stars },
  updated: new Date().toISOString().slice(0, 10),
};

console.log(`downloads: ${downloads} -> ${values.downloads}`);
console.log(`discord members: ${discordMembers} -> ${values.discordMembers}`);
console.log(`github stars: ${stars} -> ${values.githubStars}`);
console.log(`platforms (manual): ${PLATFORM_COUNT}`);

writeOrgStats(values);
writeComStats(values);
