// GENERATED by scripts/update-stats.mjs — do not edit by hand.
// Refresh with: pnpm stats (raw values as of 2026-09-15)
const siteStats = {
  downloads: '140k',
  discordMembers: '2.1k',
  githubStars: '280',
  platforms: '11',
} as const;

export default siteStats;
