// GENERATED by scripts/update-stats.mjs — do not edit by hand.
// Refresh with: pnpm stats (raw values as of 2026-08-27)
const siteStats = {
  downloads: '130k',
  discordMembers: '2.1k',
  githubStars: '270',
  platforms: '11',
} as const;

export default siteStats;
