// GENERATED by scripts/update-stats.mjs — do not edit by hand.
// Refresh with: pnpm stats (raw values as of 2026-07-26)
const siteStats = {
  downloads: '120k',
  discordMembers: '2k',
  githubStars: '270',
  platforms: '11',
} as const;

export default siteStats;
